markdown: kramdown
md: kramdown

title: AU Ford Falcon - SPUD Project
description: A collation of notes and information about the AU Falcon, collated while working on a Falcon Forte, nicknamed "SPUD".
baseurl: "/AU-Falcon-SPUD-Project" # the subpath of your site, e.g. /blog
url: "https://digi-ron.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  digi-ron
repository: digi-ron/AU-Falcon-SPUD-Project
lang: en-AU

# custom variable domain - for printable links from sitedump, hard-coded to avoid override of url variable
domain: "https://digi-ron.github.io/AU-Falcon-SPUD-Project/"

vehicle: "1999, 2000, 2001, and 2002 Ford Falcon AU"

# Build settings
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  - scope:
      path: "*.md"
    values:
      layout: default