markdown: kramdown
md: kramdown

title: AU Ford Falcon - SPUD Project
description: notes and information, collated while working on a Series 1 AU Falcon Forte, nicknamed "SPUD".
baseurl: "/AU-Falcon-SPUD-Project" # the subpath of your site, e.g. /blog
url: "https://digi-ron.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  digi-ron
repository: digi-ron/AU-Falcon-SPUD-Project
lang: en-AU

# custom domain variables - required for printable pages using CSS in both staticsite zip and live site
trueroot: "https://digi-ron.github.io"
domain: "https://digi-ron.github.io/AU-Falcon-SPUD-Project/"

# custom variables
feedback_link: "https://forms.gle/LjtA2fR2T1C6BPq96"
vehicle: "1999, 2000, 2001, and 2002 Ford Falcon AU"

# Build settings
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# exclude build files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# set layouts for all md files
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default