markdown: kramdown
md: kramdown

title: AU Ford Falcon - SPUD Project
email: your-email@example.com
description: A collation of notes and information about the AU Falcon, collated while working on a Falcon Forte, nicknamed "SPUD".
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://digi-ron.github.io/AU-Falcon-SPUD-Project" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  digi-ron
repository: digi-ron/AU-Falcon-SPUD-Project

# Build settings
#theme: minima
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap